In [1]:


import pandas as pd
df=pd.read_csv('weight-height.csv')
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [2]:
from sklearn.preprocessing import LabelEncoder

In [3]:
le=LabelEncoder()

In [4]:
df.Gender=le.fit_transform(df.Gender)

In [5]:
df.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

# Training model

In [6]:
x=df.drop('Weight', axis=1)

In [7]:
x

Gender     Height
0          1  73.847017
1          1  68.781904
2          1  74.110105
3          1  71.730978
4          1  69.881796
...      ...        ...
8550       0  60.483946
8551       0  63.423372
8552       0  65.584057
8553       0  67.429971
8554       0  60.921791

[8555 rows x 2 columns]

In [8]:
y=df['Weight']

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
xtrain,xtest, ytrain,ytest=train_test_split(x,y,test_size=.30)

# Linear Regression

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
lg=LinearRegression()

In [13]:
lg.fit(xtrain,ytrain)

LinearRegression()

# prediction by test data

In [14]:
prediction=lg.predict(xtest)
prediction

array([148.98205979, 140.57884271, 223.85845353, ..., 141.23316675,
       180.20427109, 183.57339324])

# Accuracy

In [15]:
from sklearn.metrics import r2_score

In [16]:
r2_score(ytest,prediction)

0.8957094823515517

# MSE

In [17]:
from sklearn.metrics import mean_squared_error


In [18]:
mean_squared_error(ytest,prediction)

104.91757787240249

# KNN Regression

In [19]:
from sklearn.neighbors import KNeighborsRegressor

In [20]:
kn=KNeighborsRegressor()

In [21]:
kn.fit(xtrain,ytrain)

KNeighborsRegressor()

In [22]:
prediction=kn.predict(xtest)
prediction

array([153.8712586 , 136.45844152, 225.82524276, ..., 145.3148024 ,
       172.29498466, 183.8961118 ])

# Accuracy

In [23]:
from sklearn.metrics import r2_score

In [24]:
r2_score(ytest,prediction)

0.8765419227448894

# MSE

In [25]:
from sklearn.metrics import mean_squared_error

In [26]:
mean_squared_error(ytest,prediction)

124.20038490990146

# Random Forest Rehressor

In [27]:
from sklearn.ensemble._forest import RandomForestRegressor

In [28]:
rfr=RandomForestRegressor()

In [29]:
rfr.fit(xtrain,ytrain)

RandomForestRegressor()

In [30]:
pre_rfr=rfr.predict(xtest)

# Accuracy

In [31]:
r2_score(ytest,pre_rfr)

0.8506297337309803

# MSE

In [32]:
mean_squared_error(ytest,pre_rfr)

150.26837431115715

# TUNING

In [71]:
import warnings

warnings.filterwarnings('ignore')

In [33]:
import numpy as np

In [34]:
n_estimators = [int(x) for x in np.linspace(5,100,15)]

max_features = ['auto', 'sqrt','log2']

max_depth = [1,2,3]

min_samples_split = [1,2,3]

min_samples_leaf = [1,2,3]

# Create ids
grids = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}
print(grids)

{'n_estimators': [5, 11, 18, 25, 32, 38, 45, 52, 59, 66, 72, 79, 86, 93, 100], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [1, 2, 3], 'min_samples_split': [1, 2, 3], 'min_samples_leaf': [1, 2, 3]}


In [35]:
from sklearn.model_selection import RandomizedSearchCV

In [36]:
rfr=RandomForestRegressor()

In [37]:
r= RandomizedSearchCV(estimator=rfr,param_distributions=grids,n_iter=100,cv=5)

In [72]:
r.fit(xtrain,ytrain)

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(), n_iter=100,
                   param_distributions={'max_depth': [1, 2, 3],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 3],
                                        'min_samples_split': [1, 2, 3],
                                        'n_estimators': [5, 11, 18, 25, 32, 38,
                                                         45, 52, 59, 66, 72, 79,
                                                         86, 93, 100]})

In [39]:
pre_r=r.predict(xtest)
pre_r

array([145.47392212, 142.86856994, 212.45719896, ..., 142.86856994,
       179.72292726, 181.45695888])

# Accuracy

In [40]:
r2_score(ytest,pre_r)

0.8814338901957137

In [41]:
r.best_params_

{'n_estimators': 100,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 'log2',
 'max_depth': 3}

# MSE

In [42]:
mean_squared_error(ytest,pre_r)

119.27900387216178

# KNN classifier

In [43]:
df=pd.read_csv('weight-height.csv')
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [44]:
df.Gender=le.fit_transform(df.Gender)
df.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [45]:
x=df.drop('Gender',axis=1)
x

Height      Weight
0     73.847017  241.893563
1     68.781904  162.310473
2     74.110105  212.740856
3     71.730978  220.042470
4     69.881796  206.349801
...         ...         ...
8550  60.483946  110.565497
8551  63.423372  129.921671
8552  65.584057  155.942671
8553  67.429971  151.678405
8554  60.921791  131.253738

[8555 rows x 2 columns]

In [46]:
y=df['Gender']
y

0       1
1       1
2       1
3       1
4       1
       ..
8550    0
8551    0
8552    0
8553    0
8554    0
Name: Gender, Length: 8555, dtype: int32

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
xtrain,xtest, ytrain,ytest=train_test_split(x,y,test_size=.30)

In [49]:
from sklearn.neighbors import KNeighborsClassifier

In [50]:
knc=KNeighborsClassifier()

In [51]:
knc.fit(xtrain,ytrain)

KNeighborsClassifier()

In [52]:
kn_predict=knc.predict(xtest)
kn_predict

array([1, 0, 1, ..., 1, 1, 1])

# Accuracy

In [53]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,roc_curve,auc

In [54]:
accuracy_score(ytest,kn_predict)

0.913517724970783

In [55]:
confusion_matrix(ytest,kn_predict)

array([[ 922,  136],
       [  86, 1423]], dtype=int64)

In [56]:
print(classification_report(ytest,kn_predict))

              precision    recall  f1-score   support

           0       0.91      0.87      0.89      1058
           1       0.91      0.94      0.93      1509

    accuracy                           0.91      2567
   macro avg       0.91      0.91      0.91      2567
weighted avg       0.91      0.91      0.91      2567



In [57]:
roc_curve(ytest,kn_predict)

(array([0.        , 0.12854442, 1.        ]),
 array([0.        , 0.94300861, 1.        ]),
 array([2, 1, 0]))

In [58]:
xtest_Height = xtest.Height
xtest_weight = xtest.Weight

In [59]:
xtest_Height =sorted(xtest_Height)

In [60]:
auc(xtest_Height ,kn_predict)

16.635779600000028

# Tuning

In [61]:
from sklearn.ensemble._forest import RandomForestClassifier


In [62]:
rfc=RandomForestClassifier()

In [63]:
ra= RandomizedSearchCV(estimator=rfc,param_distributions=grids,n_iter=100,cv=5)

In [ ]:
ra.fit(xtrain,ytrain)

In [65]:
rfc_prediction=ra.predict(xtest)
rfc_prediction

array([1, 0, 0, ..., 1, 1, 0])

In [66]:
accuracy_score(ytest,rfc_prediction)


0.9104012465913518

In [67]:
print(classification_report(ytest,kn_predict))

              precision    recall  f1-score   support

           0       0.91      0.87      0.89      1058
           1       0.91      0.94      0.93      1509

    accuracy                           0.91      2567
   macro avg       0.91      0.91      0.91      2567
weighted avg       0.91      0.91      0.91      2567



In [68]:
confusion_matrix(ytest,kn_predict)

array([[ 922,  136],
       [  86, 1423]], dtype=int64)

In [69]:
roc_curve(ytest,rfc_prediction)

(array([0.        , 0.12570888, 1.        ]),
 array([0.        , 0.93571902, 1.        ]),
 array([2, 1, 0]))

In [70]:
auc(xtest_Height ,rfc_prediction)

15.54406427999998